version: '3.5'

services:
  db:
    image: alx99/priv:botpotdb
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"
    networks: [net]

  botpot:
    image: alx99/priv:botpot
    restart: always
    env_file: botpot.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./build/keys:/keys:ro
    ports:
      - "22:2000"
    networks: [internal, net]
    depends_on:
      - db

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "80:3000"
    networks: [net]
    environment:
      PG_USER: postgres
      PG_PASSWORD: example
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin_password
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    secrets:
      - admin_password
    depends_on:
      - db
    profiles:
      - grafana

volumes:
  grafana-data:

secrets:
  admin_password:
    file: ./pw.txt

networks:
  internal:
    driver: bridge
    internal: true
  net:
    driver: bridge
