version: '3.5'

services:
  db:
    image: alx99/priv:botpotdb
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"
    networks: [net]

  botpot:
    image: alx99/priv:botpot
    restart: always
    env_file: botpot.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./build/keys:/keys:ro
    ports:
      - "22:2000"
    depends_on:
      - db
    networks: [internal, net]

#   grafana:
#     image: grafana/grafana-oss
#     restart: always
#     network_mode: host
networks:
  internal:
    driver: bridge
    internal: true
  net:
    driver: bridge
