version: '3.5'

services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"
