version: '3.5'

services:
  db:
    image: sshpotdb:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"

  botpot:
    image: botpot:latest
    restart: always
    env_file: botpot.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./build/keys:/keys:ro
    ports:
      - "127.0.0.1:2000:2000"
    depends_on:
      - db

#   grafana:
#     image: grafana/grafana-oss
#     restart: always
#     network_mode: host
