version: 3

vars:
  COMMIT_HASH: { sh: git log -n1 --format=%h }
  DATE: '{{now | date "2006-01-02T15:04:05Z07:00"}}'

tasks:
  clean:
    - rm -rf ./build
    - docker-compose down

  build:
    sources:
      - ./internal/**/*.go
      - ./cmd/botpot/main.go
    generates:
      - ./build/botpot
    cmds:
      - CGO_ENABLED=0 go build -v -trimpath -ldflags "-s -w -X 'main.commitHash={{.COMMIT_HASH}}' -X 'main.compilationDate={{.DATE}}'" -o ./build/botpot ./cmd/botpot/main.go

  test:
    deps:
      - start
    cmds:
      - defer: { task: stop }
      - defer: sh -c 'docker container stop {{.TEST_IMAGE}}; docker container rm {{.TEST_IMAGE}}'
      - sleep 1 # Takes a while for SSH server to start
      - robot -X --exitonerror ./tests/e2e.robot
    vars:
      TEST_IMAGE: { sh: docker run -d -p 2001:22 honeypot:latest }

  start:
    deps: [image]
    cmds:
      - docker-compose up -d

  stop:
    - docker-compose stop

  image:
    deps:
      - task: build
      - task: keys
      - task: docker-build
        vars:
          DOCKER_FILE: honeypot/Dockerfile
          DOCKER_IMAGE: honeypot:latest
      - task: docker-build
        vars:
          DOCKER_IMAGE: sshpotdb:latest
          DIR: ./db
    cmds:
      - task: docker-build
        vars:
          DOCKER_IMAGE: botpot:latest

  docker-build:
    label: image {{.DOCKER_IMAGE}}
    internal: true
    run: when_changed
    cmds:
      - cd {{.DIR}} && docker build --file {{.DOCKER_FILE}} -t {{.DOCKER_IMAGE}} .
    vars:
      DOCKER_FILE: '{{default "Dockerfile" .DOCKER_FILE}}'
      DIR: '{{default "." .DIR}}'

  keys:
    cmds:
      - mkdir -p {{.KEY_DIR}}
      - ssh-keygen -t rsa -N "" -f {{.KEY_DIR}}/rsa.pem
      - ssh-keygen -t ed25519 -N "" -f {{.KEY_DIR}}/ed25519.pem
      - ssh-keygen -t ecdsa -b 256 -N "" -f {{.KEY_DIR}}/ecdsa256.pem
      - ssh-keygen -t ecdsa -b 384 -N "" -f {{.KEY_DIR}}/ecdsa384.pem
      - ssh-keygen -t ecdsa -b 521 -N "" -f {{.KEY_DIR}}/ecdsa521.pem
    status:
      - test -f {{.KEY_DIR}}/rsa.pem
      - test -f {{.KEY_DIR}}/ed25519.pem
      - test -f {{.KEY_DIR}}/ecdsa256.pem
      - test -f {{.KEY_DIR}}/ecdsa384.pem
      - test -f {{.KEY_DIR}}/ecdsa521.pem
    vars:
      KEY_DIR: ./build/keys
