version: 3

includes:
  common:
    taskfile: ./task/Taskfile.yml
    internal: true
    aliases:
      - c

tasks:
  default:
    - task: start

  clean:
    desc: clean ./build and docker
    cmds:
      - rm -rf ./build
      - docker-compose down

  lint:
    desc: lint project
    cmds:
      - task: c:lint:go

  test:
    desc: test project
    deps:
      - start
    cmds:
      - defer: { task: stop }
      - defer: sh -c 'docker container stop {{.TEST_IMAGE}}; docker container rm {{.TEST_IMAGE}}'
      - sleep 1 # Takes a while for SSH server to start
      - robot -X --exitonerror ./tests/e2e.robot
    vars:
      TEST_IMAGE: { sh: docker run -d -p 2001:22 alx99/honeypot:latest }

  build:
    desc: build project
    sources:
      - ./internal/**/*.go
      - ./cmd/botpot/main.go
      - ./go.mod
    generates:
      - ./build/botpot
    cmds:
      - CGO_ENABLED=0 go build -v -trimpath -ldflags "-s -w -X 'main.commitHash={{.COMMIT_HASH}}' -X 'main.compilationDate={{.DATE}}'" -o ./build/botpot ./cmd/botpot/main.go

  start:
    desc: start project
    deps: [image, keys]
    cmds:
      - docker-compose up -d

  stop:
    desc: stop project
    cmds:
      - docker-compose stop

  image:
    desc: build project images
    deps:
      - task: build
      - task: c:docker:build
        vars:
          DOCKER_FILE: honeypot/Dockerfile
          IMAGE_NAME: alx99/honeypot:latest
    cmds:
      - task: c:docker:build
        vars:
          IMAGE_NAME: alx99/botpot:latest

  keys:
    desc: generate crypto keys
    cmds:
      - mkdir -p {{.KEY_DIR}}
      - ssh-keygen -t rsa -N "" -f {{.KEY_DIR}}/rsa.pem
      - ssh-keygen -t ed25519 -N "" -f {{.KEY_DIR}}/ed25519.pem
      - ssh-keygen -t ecdsa -b 256 -N "" -f {{.KEY_DIR}}/ecdsa256.pem
      - ssh-keygen -t ecdsa -b 384 -N "" -f {{.KEY_DIR}}/ecdsa384.pem
      - ssh-keygen -t ecdsa -b 521 -N "" -f {{.KEY_DIR}}/ecdsa521.pem
    status:
      - test -f {{.KEY_DIR}}/rsa.pem
      - test -f {{.KEY_DIR}}/ed25519.pem
      - test -f {{.KEY_DIR}}/ecdsa256.pem
      - test -f {{.KEY_DIR}}/ecdsa384.pem
      - test -f {{.KEY_DIR}}/ecdsa521.pem
    vars:
      KEY_DIR: ./build/keys
