{
 "title": "Botpot",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Sessions/hour",
   "type": "timeseries",
   "description": "SSH sessions per hour",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n$__timeGroupAlias(\"start_ts\", 1h),\ncount(*) as \"sessions\"\nFROM session \nWHERE\n$__timeFilter(start_ts)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Last 20 executed commands",
   "type": "table",
   "description": "Displays the last 20 executed exec requests",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT command\nFROM execrequest \nLIMIT 20"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Exec Requests",
   "type": "gauge",
   "description": "Number of executed exec requests",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM execrequest \nWHERE ts >= $__timeFrom() and ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "Shell Requests",
   "type": "gauge",
   "description": "Number of completed shell requests",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM shellrequest \nWHERE ts >= $__timeFrom() and ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "PTY Requests",
   "type": "gauge",
   "description": "Number of completed pty requests",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM ptyrequest \nWHERE ts >= $__timeFrom() and ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "gauge",
   "description": "Number of SSH channels opened",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM channel \nWHERE start_ts >= $__timeFrom() and start_ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "IPs",
   "type": "gauge",
   "description": "Number of unique attacker IP addresses",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM ip LIMIT 50 "
    }
   ]
  },
  {
   "title": "Subsystem Requests",
   "type": "gauge",
   "description": "Number of subsystem requests",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM SubSystemRequest \nWHERE ts >= $__timeFrom() and ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "Environment Requests",
   "type": "gauge",
   "description": "Number of environment requests",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM EnvironmentRequest \nWHERE ts >= $__timeFrom() and ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "WinDemChange Requests",
   "type": "gauge",
   "description": "Number of window dimension change requests",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM WindowDimChangeRequest \nWHERE ts >= $__timeFrom() and ts <= $__timeTo() "
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "gauge",
   "description": "Number of completed SSH sessions",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM session\nWHERE start_ts >= $__timeFrom() and start_ts <= $__timeTo() "
    }
   ]
  }
 ]
}