name: Docker Image CI

on:
  - workflow_dispatch
  - push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Install task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: test
        run: go env
      - name: Build the Docker image
        run: task image
