name: Docker Image CI

on:
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Build docker images
        run: ./bin/task image
      - name: Push docker images
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u alx99 --password-stdin docker.io
          docker push docker.io/alx99/botpot:latest
          docker push docker.io/alx99/honeypot:latest
